// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: vibe/workspace/v1/workspace.proto

package workspacev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ---------------- 沙箱状态枚举 ----------------
type WorkspaceStatus int32

const (
	WorkspaceStatus_WORKSPACE_STATUS_UNSPECIFIED WorkspaceStatus = 0
	WorkspaceStatus_WORKSPACE_STATUS_STARTING    WorkspaceStatus = 1 // 正在拉取镜像/启动中
	WorkspaceStatus_WORKSPACE_STATUS_RUNNING     WorkspaceStatus = 2 // 正常运行，终端可连
	WorkspaceStatus_WORKSPACE_STATUS_STOPPED     WorkspaceStatus = 3 // 已暂停/休眠
	WorkspaceStatus_WORKSPACE_STATUS_FAILED      WorkspaceStatus = 4 // 启动失败或意外崩溃
)

// Enum value maps for WorkspaceStatus.
var (
	WorkspaceStatus_name = map[int32]string{
		0: "WORKSPACE_STATUS_UNSPECIFIED",
		1: "WORKSPACE_STATUS_STARTING",
		2: "WORKSPACE_STATUS_RUNNING",
		3: "WORKSPACE_STATUS_STOPPED",
		4: "WORKSPACE_STATUS_FAILED",
	}
	WorkspaceStatus_value = map[string]int32{
		"WORKSPACE_STATUS_UNSPECIFIED": 0,
		"WORKSPACE_STATUS_STARTING":    1,
		"WORKSPACE_STATUS_RUNNING":     2,
		"WORKSPACE_STATUS_STOPPED":     3,
		"WORKSPACE_STATUS_FAILED":      4,
	}
)

func (x WorkspaceStatus) Enum() *WorkspaceStatus {
	p := new(WorkspaceStatus)
	*p = x
	return p
}

func (x WorkspaceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkspaceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_vibe_workspace_v1_workspace_proto_enumTypes[0].Descriptor()
}

func (WorkspaceStatus) Type() protoreflect.EnumType {
	return &file_vibe_workspace_v1_workspace_proto_enumTypes[0]
}

func (x WorkspaceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkspaceStatus.Descriptor instead.
func (WorkspaceStatus) EnumDescriptor() ([]byte, []int) {
	return file_vibe_workspace_v1_workspace_proto_rawDescGZIP(), []int{0}
}

// ---------------- 启动沙箱 ----------------
type StartWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`          // 全局唯一的沙箱ID (由 Java 控制面生成下发)
	StudentId     string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`                // 学生唯一标识
	CourseId      string                 `protobuf:"bytes,3,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`                   // 关联的课程/任务标识
	BaseImage     string                 `protobuf:"bytes,4,opt,name=base_image,json=baseImage,proto3" json:"base_image,omitempty"`                // 基础镜像名 (如: vibe-python-base:latest)
	CpuLimitM     int32                  `protobuf:"varint,5,opt,name=cpu_limit_m,json=cpuLimitM,proto3" json:"cpu_limit_m,omitempty"`             // CPU 限制 (例如 1000m = 1 core)
	MemoryLimitMb int32                  `protobuf:"varint,6,opt,name=memory_limit_mb,json=memoryLimitMb,proto3" json:"memory_limit_mb,omitempty"` // 内存限制 (MB)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartWorkspaceRequest) Reset() {
	*x = StartWorkspaceRequest{}
	mi := &file_vibe_workspace_v1_workspace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkspaceRequest) ProtoMessage() {}

func (x *StartWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_workspace_v1_workspace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*StartWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_vibe_workspace_v1_workspace_proto_rawDescGZIP(), []int{0}
}

func (x *StartWorkspaceRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *StartWorkspaceRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *StartWorkspaceRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *StartWorkspaceRequest) GetBaseImage() string {
	if x != nil {
		return x.BaseImage
	}
	return ""
}

func (x *StartWorkspaceRequest) GetCpuLimitM() int32 {
	if x != nil {
		return x.CpuLimitM
	}
	return 0
}

func (x *StartWorkspaceRequest) GetMemoryLimitMb() int32 {
	if x != nil {
		return x.MemoryLimitMb
	}
	return 0
}

type StartWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`            // 回传沙箱ID
	ContainerId   string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`            // Docker/K8s 分配的底层容器ID
	PtyWsUrl      string                 `protobuf:"bytes,3,opt,name=pty_ws_url,json=ptyWsUrl,proto3" json:"pty_ws_url,omitempty"`                   // 终端 WebSocket 代理地址 (学生连这个地址敲命令)
	Status        WorkspaceStatus        `protobuf:"varint,4,opt,name=status,proto3,enum=vibe.workspace.v1.WorkspaceStatus" json:"status,omitempty"` // 当前状态
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`         // 错误信息（如果启动失败）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartWorkspaceResponse) Reset() {
	*x = StartWorkspaceResponse{}
	mi := &file_vibe_workspace_v1_workspace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkspaceResponse) ProtoMessage() {}

func (x *StartWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_workspace_v1_workspace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*StartWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_vibe_workspace_v1_workspace_proto_rawDescGZIP(), []int{1}
}

func (x *StartWorkspaceResponse) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *StartWorkspaceResponse) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *StartWorkspaceResponse) GetPtyWsUrl() string {
	if x != nil {
		return x.PtyWsUrl
	}
	return ""
}

func (x *StartWorkspaceResponse) GetStatus() WorkspaceStatus {
	if x != nil {
		return x.Status
	}
	return WorkspaceStatus_WORKSPACE_STATUS_UNSPECIFIED
}

func (x *StartWorkspaceResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// ---------------- 停止沙箱 ----------------
type StopWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopWorkspaceRequest) Reset() {
	*x = StopWorkspaceRequest{}
	mi := &file_vibe_workspace_v1_workspace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopWorkspaceRequest) ProtoMessage() {}

func (x *StopWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_workspace_v1_workspace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*StopWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_vibe_workspace_v1_workspace_proto_rawDescGZIP(), []int{2}
}

func (x *StopWorkspaceRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

type StopWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopWorkspaceResponse) Reset() {
	*x = StopWorkspaceResponse{}
	mi := &file_vibe_workspace_v1_workspace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopWorkspaceResponse) ProtoMessage() {}

func (x *StopWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_workspace_v1_workspace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*StopWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_vibe_workspace_v1_workspace_proto_rawDescGZIP(), []int{3}
}

func (x *StopWorkspaceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopWorkspaceResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// ---------------- 查询状态 ----------------
type GetWorkspaceStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkspaceStatusRequest) Reset() {
	*x = GetWorkspaceStatusRequest{}
	mi := &file_vibe_workspace_v1_workspace_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkspaceStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkspaceStatusRequest) ProtoMessage() {}

func (x *GetWorkspaceStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_workspace_v1_workspace_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkspaceStatusRequest.ProtoReflect.Descriptor instead.
func (*GetWorkspaceStatusRequest) Descriptor() ([]byte, []int) {
	return file_vibe_workspace_v1_workspace_proto_rawDescGZIP(), []int{4}
}

func (x *GetWorkspaceStatusRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

type GetWorkspaceStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Status        WorkspaceStatus        `protobuf:"varint,2,opt,name=status,proto3,enum=vibe.workspace.v1.WorkspaceStatus" json:"status,omitempty"`
	PtyWsUrl      string                 `protobuf:"bytes,3,opt,name=pty_ws_url,json=ptyWsUrl,proto3" json:"pty_ws_url,omitempty"`               // 如果运行中，返回 PTY 地址
	UptimeSeconds int64                  `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"` // 已运行时长
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkspaceStatusResponse) Reset() {
	*x = GetWorkspaceStatusResponse{}
	mi := &file_vibe_workspace_v1_workspace_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkspaceStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkspaceStatusResponse) ProtoMessage() {}

func (x *GetWorkspaceStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_workspace_v1_workspace_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkspaceStatusResponse.ProtoReflect.Descriptor instead.
func (*GetWorkspaceStatusResponse) Descriptor() ([]byte, []int) {
	return file_vibe_workspace_v1_workspace_proto_rawDescGZIP(), []int{5}
}

func (x *GetWorkspaceStatusResponse) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *GetWorkspaceStatusResponse) GetStatus() WorkspaceStatus {
	if x != nil {
		return x.Status
	}
	return WorkspaceStatus_WORKSPACE_STATUS_UNSPECIFIED
}

func (x *GetWorkspaceStatusResponse) GetPtyWsUrl() string {
	if x != nil {
		return x.PtyWsUrl
	}
	return ""
}

func (x *GetWorkspaceStatusResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

// ---------------- 销毁沙箱 ----------------
type DestroyWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyWorkspaceRequest) Reset() {
	*x = DestroyWorkspaceRequest{}
	mi := &file_vibe_workspace_v1_workspace_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyWorkspaceRequest) ProtoMessage() {}

func (x *DestroyWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_workspace_v1_workspace_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*DestroyWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_vibe_workspace_v1_workspace_proto_rawDescGZIP(), []int{6}
}

func (x *DestroyWorkspaceRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

type DestroyWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyWorkspaceResponse) Reset() {
	*x = DestroyWorkspaceResponse{}
	mi := &file_vibe_workspace_v1_workspace_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyWorkspaceResponse) ProtoMessage() {}

func (x *DestroyWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vibe_workspace_v1_workspace_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*DestroyWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_vibe_workspace_v1_workspace_proto_rawDescGZIP(), []int{7}
}

func (x *DestroyWorkspaceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DestroyWorkspaceResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_vibe_workspace_v1_workspace_proto protoreflect.FileDescriptor

const file_vibe_workspace_v1_workspace_proto_rawDesc = "" +
	"\n" +
	"!vibe/workspace/v1/workspace.proto\x12\x11vibe.workspace.v1\"\xdd\x01\n" +
	"\x15StartWorkspaceRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\x12\x1b\n" +
	"\tcourse_id\x18\x03 \x01(\tR\bcourseId\x12\x1d\n" +
	"\n" +
	"base_image\x18\x04 \x01(\tR\tbaseImage\x12\x1e\n" +
	"\vcpu_limit_m\x18\x05 \x01(\x05R\tcpuLimitM\x12&\n" +
	"\x0fmemory_limit_mb\x18\x06 \x01(\x05R\rmemoryLimitMb\"\xdd\x01\n" +
	"\x16StartWorkspaceResponse\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\x12\x1c\n" +
	"\n" +
	"pty_ws_url\x18\x03 \x01(\tR\bptyWsUrl\x12:\n" +
	"\x06status\x18\x04 \x01(\x0e2\".vibe.workspace.v1.WorkspaceStatusR\x06status\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"9\n" +
	"\x14StopWorkspaceRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\"V\n" +
	"\x15StopWorkspaceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\">\n" +
	"\x19GetWorkspaceStatusRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\"\xc0\x01\n" +
	"\x1aGetWorkspaceStatusResponse\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12:\n" +
	"\x06status\x18\x02 \x01(\x0e2\".vibe.workspace.v1.WorkspaceStatusR\x06status\x12\x1c\n" +
	"\n" +
	"pty_ws_url\x18\x03 \x01(\tR\bptyWsUrl\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x03R\ruptimeSeconds\"<\n" +
	"\x17DestroyWorkspaceRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\"Y\n" +
	"\x18DestroyWorkspaceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage*\xab\x01\n" +
	"\x0fWorkspaceStatus\x12 \n" +
	"\x1cWORKSPACE_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19WORKSPACE_STATUS_STARTING\x10\x01\x12\x1c\n" +
	"\x18WORKSPACE_STATUS_RUNNING\x10\x02\x12\x1c\n" +
	"\x18WORKSPACE_STATUS_STOPPED\x10\x03\x12\x1b\n" +
	"\x17WORKSPACE_STATUS_FAILED\x10\x042\xbd\x03\n" +
	"\x10WorkspaceService\x12e\n" +
	"\x0eStartWorkspace\x12(.vibe.workspace.v1.StartWorkspaceRequest\x1a).vibe.workspace.v1.StartWorkspaceResponse\x12b\n" +
	"\rStopWorkspace\x12'.vibe.workspace.v1.StopWorkspaceRequest\x1a(.vibe.workspace.v1.StopWorkspaceResponse\x12q\n" +
	"\x12GetWorkspaceStatus\x12,.vibe.workspace.v1.GetWorkspaceStatusRequest\x1a-.vibe.workspace.v1.GetWorkspaceStatusResponse\x12k\n" +
	"\x10DestroyWorkspace\x12*.vibe.workspace.v1.DestroyWorkspaceRequest\x1a+.vibe.workspace.v1.DestroyWorkspaceResponseB\x86\x01\n" +
	"\x1bcom.vibecoding.workspace.v1B\x0eWorkspaceProtoP\x01ZUgithub.com/hyqxyd/vibe-coding-project/backend-data-plane/api/workspace/v1;workspacev1b\x06proto3"

var (
	file_vibe_workspace_v1_workspace_proto_rawDescOnce sync.Once
	file_vibe_workspace_v1_workspace_proto_rawDescData []byte
)

func file_vibe_workspace_v1_workspace_proto_rawDescGZIP() []byte {
	file_vibe_workspace_v1_workspace_proto_rawDescOnce.Do(func() {
		file_vibe_workspace_v1_workspace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vibe_workspace_v1_workspace_proto_rawDesc), len(file_vibe_workspace_v1_workspace_proto_rawDesc)))
	})
	return file_vibe_workspace_v1_workspace_proto_rawDescData
}

var file_vibe_workspace_v1_workspace_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_vibe_workspace_v1_workspace_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_vibe_workspace_v1_workspace_proto_goTypes = []any{
	(WorkspaceStatus)(0),               // 0: vibe.workspace.v1.WorkspaceStatus
	(*StartWorkspaceRequest)(nil),      // 1: vibe.workspace.v1.StartWorkspaceRequest
	(*StartWorkspaceResponse)(nil),     // 2: vibe.workspace.v1.StartWorkspaceResponse
	(*StopWorkspaceRequest)(nil),       // 3: vibe.workspace.v1.StopWorkspaceRequest
	(*StopWorkspaceResponse)(nil),      // 4: vibe.workspace.v1.StopWorkspaceResponse
	(*GetWorkspaceStatusRequest)(nil),  // 5: vibe.workspace.v1.GetWorkspaceStatusRequest
	(*GetWorkspaceStatusResponse)(nil), // 6: vibe.workspace.v1.GetWorkspaceStatusResponse
	(*DestroyWorkspaceRequest)(nil),    // 7: vibe.workspace.v1.DestroyWorkspaceRequest
	(*DestroyWorkspaceResponse)(nil),   // 8: vibe.workspace.v1.DestroyWorkspaceResponse
}
var file_vibe_workspace_v1_workspace_proto_depIdxs = []int32{
	0, // 0: vibe.workspace.v1.StartWorkspaceResponse.status:type_name -> vibe.workspace.v1.WorkspaceStatus
	0, // 1: vibe.workspace.v1.GetWorkspaceStatusResponse.status:type_name -> vibe.workspace.v1.WorkspaceStatus
	1, // 2: vibe.workspace.v1.WorkspaceService.StartWorkspace:input_type -> vibe.workspace.v1.StartWorkspaceRequest
	3, // 3: vibe.workspace.v1.WorkspaceService.StopWorkspace:input_type -> vibe.workspace.v1.StopWorkspaceRequest
	5, // 4: vibe.workspace.v1.WorkspaceService.GetWorkspaceStatus:input_type -> vibe.workspace.v1.GetWorkspaceStatusRequest
	7, // 5: vibe.workspace.v1.WorkspaceService.DestroyWorkspace:input_type -> vibe.workspace.v1.DestroyWorkspaceRequest
	2, // 6: vibe.workspace.v1.WorkspaceService.StartWorkspace:output_type -> vibe.workspace.v1.StartWorkspaceResponse
	4, // 7: vibe.workspace.v1.WorkspaceService.StopWorkspace:output_type -> vibe.workspace.v1.StopWorkspaceResponse
	6, // 8: vibe.workspace.v1.WorkspaceService.GetWorkspaceStatus:output_type -> vibe.workspace.v1.GetWorkspaceStatusResponse
	8, // 9: vibe.workspace.v1.WorkspaceService.DestroyWorkspace:output_type -> vibe.workspace.v1.DestroyWorkspaceResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_vibe_workspace_v1_workspace_proto_init() }
func file_vibe_workspace_v1_workspace_proto_init() {
	if File_vibe_workspace_v1_workspace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vibe_workspace_v1_workspace_proto_rawDesc), len(file_vibe_workspace_v1_workspace_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vibe_workspace_v1_workspace_proto_goTypes,
		DependencyIndexes: file_vibe_workspace_v1_workspace_proto_depIdxs,
		EnumInfos:         file_vibe_workspace_v1_workspace_proto_enumTypes,
		MessageInfos:      file_vibe_workspace_v1_workspace_proto_msgTypes,
	}.Build()
	File_vibe_workspace_v1_workspace_proto = out.File
	file_vibe_workspace_v1_workspace_proto_goTypes = nil
	file_vibe_workspace_v1_workspace_proto_depIdxs = nil
}
